-- MySQL Script generated by MySQL Workbench
-- 11/15/14 21:42:09
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema eventcalendar
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `eventcalendar` ;
CREATE SCHEMA IF NOT EXISTS `eventcalendar` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `eventcalendar` ;

-- -----------------------------------------------------
-- Table `eventcalendar`.`Genres`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eventcalendar`.`Genres` (
  `Id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(50) NOT NULL,
  `CreationDate` DATETIME NOT NULL,
  `ModificationDate` DATETIME NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eventcalendar`.`Events`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eventcalendar`.`Events` (
  `Id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Genre_Id` INT UNSIGNED NOT NULL,
  `Name` VARCHAR(150) NOT NULL,
  `Description` TEXT NOT NULL,
  `Duration` TIME NOT NULL,
  `Cast` VARCHAR(500) NULL,
  `Image` LONGBLOB NULL,
  `ImageDescription` VARCHAR(250) NULL,
  `CreationDate` DATETIME NOT NULL,
  `ModificationDate` DATETIME NULL,
  PRIMARY KEY (`Id`),
  INDEX `idx_Genre_id` (`Genre_Id` ASC),
  CONSTRAINT `fk_Genre_Id`
    FOREIGN KEY (`Genre_Id`)
    REFERENCES `eventcalendar`.`Genres` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eventcalendar`.`Links`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eventcalendar`.`Links` (
  `Id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Event_Id` INT UNSIGNED NOT NULL,
  `URL` VARCHAR(255) NOT NULL,
  `Name` VARCHAR(50) NULL,
  `CreationDate` DATETIME NOT NULL,
  `ModificationDate` DATETIME NULL,
  PRIMARY KEY (`Id`, `Event_Id`),
  INDEX `idx_Event_Id` (`Event_Id` ASC),
  CONSTRAINT `fk_Event_Id`
    FOREIGN KEY (`Event_Id`)
    REFERENCES `eventcalendar`.`Events` (`Id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eventcalendar`.`Shows`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eventcalendar`.`Shows` (
  `Id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Event_Id` INT UNSIGNED NOT NULL,
  `Date` DATE NOT NULL,
  `Time` TIME NOT NULL,
  `CreationDate` DATETIME NOT NULL,
  `ModificationDate` DATETIME NULL,
  PRIMARY KEY (`Id`, `Event_Id`),
  INDEX `idx_Event_Id` (`Event_Id` ASC),
  CONSTRAINT `fk_Event_Id`
    FOREIGN KEY (`Event_Id`)
    REFERENCES `eventcalendar`.`Events` (`Id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eventcalendar`.`PriceGroups`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eventcalendar`.`PriceGroups` (
  `Id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(35) NOT NULL,
  `Price` DECIMAL(8,2) UNSIGNED NOT NULL,
  `CreationDate` DATETIME NOT NULL,
  `ModificationDate` DATETIME NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eventcalendar`.`Event_PriceGroups`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eventcalendar`.`Event_PriceGroups` (
  `Event_Id` INT UNSIGNED NOT NULL,
  `PriceGroup_Id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`Event_Id`, `PriceGroup_Id`),
  INDEX `idx_PriceGroup_Id` (`PriceGroup_Id` ASC),
  INDEX `idx_Event_Id` (`Event_Id` ASC),
  CONSTRAINT `fk_PriceGroup_Id`
    FOREIGN KEY (`PriceGroup_Id`)
    REFERENCES `eventcalendar`.`PriceGroups` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Event_Id`
    FOREIGN KEY (`Event_Id`)
    REFERENCES `eventcalendar`.`Events` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eventcalendar`.`Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eventcalendar`.`Users` (
  `Id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Username` VARCHAR(30) NOT NULL,
  `Password` VARCHAR(128) NOT NULL,
  `CreationDate` DATETIME NOT NULL,
  `ModificationDate` DATETIME NULL,
  PRIMARY KEY (`Id`),
  UNIQUE INDEX `idx_Username` (`Username` ASC))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
